### ISSUE TITLE
do not save file

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-core#1]
PLAY [Testing] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [en]

TASK: [debops.core | Create root directories] ********************************* 
ok: [en] => (item={'path': u'/etc/ansible/facts.d', 'fact': 'facts'})
ok: [en] => (item={'path': u'/usr/local/bin', 'fact': 'bin'})
ok: [en] => (item={'path': u'/usr/local/etc', 'fact': 'etc'})
ok: [en] => (item={'path': u'/usr/local/lib', 'fact': 'lib'})
ok: [en] => (item={'path': u'/usr/local/sbin', 'fact': 'sbin'})
ok: [en] => (item={'path': u'/usr/local/share', 'fact': 'share'})
ok: [en] => (item={'path': u'/usr/local/src', 'fact': 'src'})
ok: [en] => (item={'path': u'/srv', 'fact': 'data'})
ok: [en] => (item={'path': u'/srv', 'fact': 'srv'})
ok: [en] => (item={'path': u'/var/backups', 'fact': 'backup'})
ok: [en] => (item={'path': u'/var/local', 'fact': 'home'})
ok: [en] => (item={'path': u'/var/local', 'fact': 'app'})
ok: [en] => (item={'path': u'/var/local', 'fact': 'var'})
ok: [en] => (item={'path': u'/var/log', 'fact': 'log'})

TASK: [debops.core | Check IP address of current Ansible Controller] ********** 
ok: [en]

TASK: [debops.core | Read the host UUID] ************************************** 
ok: [en]

TASK: [debops.core | Save local facts] **************************************** 
failed: [en] => (item=core) => {"failed": true, "item": "core"}
msg: Destination /etc/ansible/facts.d not writable
failed: [en] => (item=root) => {"failed": true, "item": "root"}
msg: Destination /etc/ansible/facts.d not writable
failed: [en] => (item=tags) => {"failed": true, "item": "tags"}
msg: Destination /etc/ansible/facts.d not writable
failed: [en] => (item=uuid) => {"failed": true, "item": "uuid"}
msg: Destination /etc/ansible/facts.d not writable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
debops.core | Create root directories ---------------------------------- 37.61s
debops.core | Save local facts ----------------------------------------- 19.08s
debops.core | Read the host UUID ---------------------------------------- 2.69s
debops.core | Check IP address of current Ansible Controller ------------ 0.01s
           to retry, use: --limit @/home/le9i0nx/test.retry

en                         : ok=4    changed=0    unreachable=0    failed=1   

I tested already deployed on the car and there is already data files
```bash
  ---

  - name: Testing
    hosts: en
    roles:
      - role: debops.core
```

**Comment by drybjed** [comment]
Did you create playbook with correct `become` options? `debops.core` needs specific playbook which is run with `become: False`, but the role itself is set with `become: True`. Check in the documentation or in the `debops-playbooks` repository, `core.yml` playbook.
